language: node_js
node: 8

git:
  depth: false
  submodules: false

cache: yarn

before_install: yarn
install: ./node_modules/gitbook-cli/bin/gitbook.js install
script: ./node_modules/gitbook-cli/bin/gitbook build

